version: '3.7'
services:

  indexer:
    tty: true
    container_name: indexer
    build: .
    volumes: 
      - .conf.yaml:/app/conf.yaml
    ports:
      - "8000:8000"
    environment:
      - BLOCK_TIME=4
      - NODE_IP=stating.vsystems.dev
      - NODE_PORT=9922
      - NODE_API_KEY=mudsipecDic1950
      - NETWORK=testnet
      - DB_USER=postgres
      - DB_PASS=postgres
      - DB_IP=db
      - POSTGRES_DATABASE=indexer
    restart: always
    depends_on:
      - db

  db:
    image: postgres:14.2-alpine
    container_name: indexer_db
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DATABASE=indexer
    ports:
      - '5432:5432'
    volumes: 
      - ./database:/var/lib/postgresql/data
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
    logging:
      options:
        max-size: 10m
        max-file: "3"